site_name: The deal.II Finite Element Library
site_url:  https://www.dealii.org/
repo_name: dealii/dealii
repo_url:  https://github.com/dealii/dealii
plugins: []
nav:
  - index.md
  - Info:
    - ./info.md
    - About: ./about.md
    - Help: ./help.md
    - FAQ: https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions
    - Participate: participate.md
    - Publications: publications.md
    - License: license.md
    - Team: ./team.md
    - Wiki: https://github.com/dealii/dealii/wiki
    - Funding: ./funding
  - Current (9.6): ./current.md
  - Documentation: doc.md
  - Gallery: ./gallery.md
  - Applications: ./applications.md
  - Development:
    - development/index.md
    - Github repository: https://github.com/dealii/dealii
    - README: https://www.dealii.org/developer/readme.html
    - Doxygen documentation: https://dealii.org/developer/doxygen/deal.II
    - Code Gallery: https://dealii.org/developer/doxygen/deal.II/CodeGallery.html
    - CDash: https://cdash.dealii.org/index.php?project=deal.II
    - Performance tests: https://dealii.org/performance_tests/graphs/
markdown_extensions:
  - attr_list
  - md_in_html
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - header.autohide
    - toc.integrate
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  logo:    assets/clover57.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  homepage: https://www.dealii.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dealii/dealii
  generator: false
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2023 - 2024 by the deal.II authors
