site_name: The deal.II Finite Element Library
site_url:  https://www.dealii.org/
repo_name: dealii/dealii
repo_url:  https://github.com/dealii/dealii
plugins: []
nav:
  - Home: index.md
  - About:
    - about/index.md
    - News: about/news.md
    - Getting Help:
      - getting_help/index.md
      - FAQ: https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions
      - Wiki: https://github.com/dealii/dealii/wiki
      - Contact: getting_help/contact.md
    - Community:
      - community/index.md
      - Team: community/team.md
      - Publications: community/publications.md
      - Best papers: community/best_paper_award.md      
    - Funding: about/funding.md
  - Current Release (9.6):
    - current_release/index.md
    - Download: current_release/download.md
    - README: https://www.dealii.org/current/readme.html
    - Documentation: https://dealii.org/current/doxygen/deal.II
    - Tutorials: https://www.dealii.org/current/doxygen/deal.II/Tutorial.html
    - current_release/older_releases.md
  - Development:
    - development/index.md
    - GitHub repository: https://github.com/dealii/dealii
    - README: https://www.dealii.org/developer/readme.html
    - Documentation: https://dealii.org/developer/doxygen/deal.II
    - Tutorials: https://www.dealii.org/developer/doxygen/deal.II/Tutorial.html
    - CDash: https://cdash.dealii.org/index.php?project=deal.II
    - Performance tests: https://dealii.org/performance_tests/graphs/
  - Gallery & Applications:
    - gallery_applications/index.md
    - Image Gallery: gallery_applications/gallery.md
    - Code Gallery: https://dealii.org/developer/doxygen/deal.II/CodeGallery.html
    - gallery_applications/applications.md
markdown_extensions:
  - attr_list
  - md_in_html
  - markdown_include.include:
      base_path: docs
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.path
    - header.autohide
    - toc.integrate
    - toc.follow
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  logo:    assets/clover57.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
extra:
  homepage: https://www.dealii.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dealii/dealii
  generator: false
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2023 - 2024 by the deal.II authors
